#!/usr/bin/env bash
# One root for everything bulky, so $HOME holds only configuration.
#
# Written for CMU AFS, where $HOME (andrew space) has a small per-volume quota and
# a second, much larger volume (ece space) is available at a path like
# /afs/ece.cmu.edu/usr/<andrewid>. A normal install puts several GB in $HOME —
# toolchains, fonts, plugin trees, build output — of which only a few KB is
# actually configuration. This separates the two.
#
# Each relocation is an environment variable the tool in question already
# supports, so nothing here depends on symlinks. A symlink into a volume that is
# not mounted, or for which you hold no AFS token, fails in a way that is far
# harder to read than an unset variable.
#
# XDG_CONFIG_HOME is deliberately NOT redirected. zsh reads ~/.zshenv before any
# of this can be established, so configuration has to stay where the shell
# already looks; it is small enough not to matter.

DATA_ROOT_ENV_FILE_DEFAULT="$HOME/.dotfiles-env"

# data_root_exports ROOT — the assignments, one per line.
#
# The same text is both sourced by the shell and eval'd by the installer, so the
# two cannot drift. $PATH is escaped: it must expand when the line runs, not now.
#
# printf is a builtin; cat is not. This has to keep working when it is called to
# repair a PATH that does not yet resolve anything.
data_root_exports() {
  local root="${1%/}"
  printf 'export DOTFILES_DATA_ROOT="%s"\n' "$root"
  printf 'export XDG_DATA_HOME="%s/share"\n' "$root"
  printf 'export XDG_STATE_HOME="%s/state"\n' "$root"
  printf 'export XDG_CACHE_HOME="%s/cache"\n' "$root"
  # The prefix IS the root: portable_install puts binaries in its bin/.
  printf 'export PORTABLE_PREFIX="%s"\n' "$root"
  printf 'export CARGO_HOME="%s/cargo"\n' "$root"
  printf 'export RUSTUP_HOME="%s/rustup"\n' "$root"
  printf 'export ZSH="%s/oh-my-zsh"\n' "$root"
  printf 'export NVM_DIR="%s/nvm"\n' "$root"
  printf 'export npm_config_cache="%s/cache/npm"\n' "$root"
  printf 'export CLAUDE_CONFIG_DIR="%s/claude"\n' "$root"
  # The context-manager source is a submodule inside this repo and is small
  # enough to leave alone; its Rust build output is the part measured in GB.
  printf 'export CARGO_TARGET_DIR="%s/cargo-target"\n' "$root"
  # shellcheck disable=SC2016  # $PATH must expand when the line runs, not here.
  printf 'export PATH="%s/bin:%s/cargo/bin:$PATH"\n' "$root" "$root"
}

apply_data_root() {
  eval "$(data_root_exports "$1")"
}

ensure_data_root() {
  local root="${1%/}"

  if [ "${DRY_RUN:-0}" = "1" ]; then
    log_dry "create data root $root"
    return 0
  fi

  if [ ! -d "$root" ] && ! mkdir -p "$root" 2>/dev/null; then
    log_fail "could not create data root: $root"
    # On AFS the usual cause is a missing token or an ACL without insert rights,
    # neither of which looks like a permission error to mkdir.
    case "$root" in
      /afs/*) log_followup "on AFS check: fs listacl $(dirname "$root") — and that you hold a token (klist)" ;;
    esac
    return 1
  fi

  if [ ! -w "$root" ]; then
    log_fail "data root is not writable: $root"
    return 1
  fi

  log_ok "data root: $root"
}

# write_data_root_env ROOT [FILE] — the file ~/.zshenv sources, so that every
# later shell resolves the same locations this install used. Rewritten whole
# rather than appended, so re-running with a different root cannot leave two
# conflicting definitions behind.
write_data_root_env() {
  local root="${1%/}"
  local file="${2:-$DATA_ROOT_ENV_FILE_DEFAULT}"

  if [ "${DRY_RUN:-0}" = "1" ]; then
    log_dry "write $file pointing at $root"
    return 0
  fi

  {
    printf '# Generated by install.sh --data-root. Do not edit; re-run the installer.\n'
    printf '# Machine-specific by nature, which is why it is here and not in the repo.\n'
    data_root_exports "$root"
  } > "$file" || { log_fail "could not write $file"; return 1; }

  log_ok "wrote $file"
}
